spring:
  application:
    name: currency-conversion-service
  data:
    mongodb:
      uri: ${MONGO_URI}

request:
  limit:
    weekday: 100
    weekend: 200

logging:
  level:
    org:
      springframework:
        security: DEBUG
