spring:
  application:
    name: currency-conversion-service
  data:
    mongodb:
      uri: mongodb+srv://treat:homeAssignmen-tzfcqpn@cluster0.hefibvo.mongodb.net/CurrencyConversions?retryWrites=true&w=majority&appName=Cluster0

request:
  limit:
    weekday: 100
    weekend: 200

logging:
  level:
    org:
      springframework:
        security: DEBUG
